modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Kotori316/Dumper/issues"
[[mods]]
modId="kotori_dumper"
version="${file.jarVersion}"
displayName="Dumper"
displayURL="https://github.com/Kotori316/Dumper"
credits="Kotori316"
authors="Kotori316"
description='''
Output much info.'''
[[dependencies.fluidtank]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluidtank]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,)"
    ordering="NONE"
    side="BOTH"
