modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Kotori316/Dumper/issues"
license="All Rights Reserved."
[[mods]]
modId="kotori_dumper"
version="${file.jarVersion}"
displayName="Dumper"
displayURL="https://github.com/Kotori316/Dumper"
credits="Kotori316"
authors="Kotori316"
description='''
Output much info.'''
[[dependencies.fluidtank]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluidtank]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
