modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/Kotori316/Dumper/issues"
license = "All Rights Reserved."
[[mods]]
modId = "kotori_dumper"
version = "${file.jarVersion}"
displayName = "Dumper"
displayURL = "https://github.com/Kotori316/Dumper"
credits = "Kotori316"
authors = "Kotori316"
description = '''
Output much info.'''
[[dependencies.kotori_dumper]]
modId = "forge"
mandatory = true
versionRange = "[41.0.94,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.kotori_dumper]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
