name: Publish

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  github-context:
    runs-on: ubuntu-latest
    name: Log Debug Info
    steps:
      - name: Log
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
        
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kotori316/fictional-meme/fictional-meme:1.18.1
      credentials:
        username: kotori316
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Precompile
      run: chmod +x ./gradlew && ./gradlew compileScala --continue --stacktrace
    - name: Build
      run: chmod +x ./gradlew && ./gradlew build githubRelease --stacktrace --warning-mode all --continue
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
